import numpy as np
# Creating array
a = np.array([2,3.2,4])
print("Creating an array")
print(a)
print("-------------------")
print("finding the type(float,int,char) of array ")
print(a.dtype.name)
print("-------------------")
print("finding the dimension of of array ")
print(a.ndim)
print("-------------------")
print("finding the shape(no of col, no of row) of of array ")
print(a.shape)
print("-------------------")
print("finding the type of element of of array ")
print(type(a))
print("-------------------")
# Multidimention array
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
print("finding the type(float,int,char) of array ")
print(b.dtype.name)
print("-------------------")
print("finding the dimension of of array ")
print(b.ndim)
print("-------------------")
print("finding the shape(no of col, no of row) of of array ")
print(b.shape)
print("-------------------")
print("finding the type of element of of array ")
print(type(b))
print("-------------------")

# Complex term in array
c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)
print("-------------------")
print("finding the type(float,int,char) of array ")
print(c.dtype.name)
print("-------------------")
print("finding the dimension of of array ")
print(c.ndim)
print("-------------------")
print("finding the shape(no of col, no of row) of of array ")
print(c.shape)
print("-------------------")
print("finding the type of element of of array ")
print(type(c))
print("-------------------")
#Creating Zeros & Ones array
d = np.zeros((3,4))
print("Zeros matrix of 3X4 ")
print(d)
print("-------------------")
d = np.ones((2,3,4),dtype=np.int16)
print("Zeros matrix of 3X4 ")
print(d)
print("-------------------")
print(np.empty((2,3)))
print("-------------------")

#arange function to create sequence of no analogues to range
e = np.arange(10,30,5) #10 15 20 25 30
print("arange for creating seqeunce of  no")
print(e)
e = np.arange(0,2,0.3) #10 15 20 25 30
print("-------------------")
print("arange for creating seqeunce of  no decimals")
print(e)
#When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:
from numpy import pi
linespace_= np.linspace(0,2,9)
print("-------------------")
print("Printing 9 no from 0 to 9")
print(linespace_)
linespace_= np.linspace(0,2*pi,100)
sin = np.sin(linespace_)
print("-------------------")
print("Print 100 values of sin from 0 to 2pi")
print(sin)

# Creating array of of various size or dim using arange & reshape
a = np.arange(6)
print("-------------------")
print("One Dimension array")
print(a)
a = np.arange(12).reshape(4,3)
print("-------------------")
print("two Dimension array")
print(a)
a = np.arange(24).reshape(4,2,3)
print("-------------------")
print("Three 3D/ Dimension array")
print(a)
a = np.arange(10000).reshape(100,100)
print("-------------------")
print("100 X100 array")
print(a)

# Basic Operation of Array using Arithmatic operators
a = np.array([20,30,40,50])
print("-------------------")
print("Array a")
print(c)
b = np.arange(4)
print("-------------------")
print("Array b")
print(c)
c = a-b
print("Subtraction of array a -b")
print(c)