import numpy
# Creating array
a = numpy.array([2,3.2,4])
print("Creating an array")
print(a)
print("-------------------")
print("finding the type(float,int,char) of array ")
print(a.dtype.name)
print("-------------------")
print("finding the dimension of of array ")
print(a.ndim)
print("-------------------")
print("finding the shape(no of col, no of row) of of array ")
print(a.shape)
print("-------------------")
print("finding the type of element of of array ")
print(type(a))
print("-------------------")